name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Generate PDF's
      run: bun generate

    - name: Upload PDF's
      run: |
        for file in ./storage/*.pdf; do
          echo "$file"
        	gh release upload ${{github.event.release.tag_name}} "$file"
        done

      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
