name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: bun install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: bun generate

    - name: Upload PDF's
      run: |
        for filename in ./storage/*.pdf; do
          echo $filename
        	gh release upload ${{github.event.release.tag_name}} ./storage/$filename
        done

      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
